# Key Knowledge Gaps
1. Additional climate variables.—Our analysis provides a critical local look at changes for two important climate variables, precipitation and temperature. However, Montana’s climate and its impacts go beyond these. A more in depth downscaling effort that involves physics based models will be required to evaluate two additional important variables, evapotranspiration and drought.
2. Land use and land cover change.—Most climate analyses do not account for changes in land cover with climatic trends. However, interactions between climate, vegetation cover, and land use quality are tightly coupled. For example, with changes in temperature and precipitation, ecosystems within Montana may shift to drier conditions resulting in changes to vegetation types. This would contribute to a difference in evapotranspiration rates and aridity.
3. Precipitation timing and form.—We took a first look at changes in Montana’s precipitation. However, it is well known that the timing (winter versus spring and summer) and form (rain versus snow) of Montana’s precipitation is critical for areas such as water, forests, and agriculture resources. More work that incorporates physically based, distributed hydrological models is required to understand how our precipitation distribution will change in both space (low elevations to mountaintops) and time.
