---
params: 
  location: "Montana"
  asset_dir: "./assets"
  attr_id: "Division"
  attr_name: "Climate Division"
  attr_plural: "Climate Divisions"
  
---

```{r echo=FALSE}

shp <- sf::read_sf(file.path(params$asset_dir, "agg_regions.geojson"))

historical_table <- 
  list.files(params$asset_dir, pattern = "historical_seasonal.tif", full.names = T) %>% 
  purrr::map(function(x) {
    x %>% 
      terra::rast() %>% 
      normals::spat_summary(shp, params$attr_id, "season", "mean") %>%
      dplyr::mutate(f = x)
  })
```

# Historical Climate
## Climate Conditions 1981 - 2020
To assess `r params$location`’s current climate, we analyzed climate variable data (see sidebar) provided as 3-decade of gridMET climate data @gridmet. In this section, we review average temperature and precipitation conditions from 1981-2010 as an indicator of current climate conditions. 

::: {.callout-note icon=false}
### Climate Variables {#climate-callout}

In analyses of climate, scientists employ a suite of 50 essential climate variables to unify discussions (Global Climate Observing System undated). For this assessment, we primarily focus on just two: how climate change will affect Montana’s temperature and precipitation in the future. 

- Temperature is an objective measure of how hot or cold and object is with reference to some standard value. Temperature differences across the Earth result primarily from regional differences in absorbed solar radiation. Seasonal variations in temperature result from the tilt of the Earth’s axis as it rotates around the sun. 

- Precipitation is the quantity of water (solid or liquid) falling to the Earth’s surface at a specific place during a given period. Like temperature, precipitation varies seasonally and from place to place. Precipitation amounts can have a dramatic impact on local environmental conditions, such as abundance of wildlife or potential for crop production.
:::

### Temperature
Table 2-1 shows the average seasonal temperature variation across `r params$location`’s `r nrow(shp)` `r params$attr_plural` (Figure 2-3) from 1981-2010. Temperatures vary across `r params$location`, with average annual values ranging from `r -9999` to `r -9999` across the region. 

**Temperature Table**

Winters in Montana are cold, with statewide average temperatures of 22°F (-5.6°C). Between cold waves there are often periods of mild, windy weather in central Montana created by persistent, moist Pacific air masses on the west side of the Continental Divide, and the drying and warming effects as air descends on the east side of the Rockies. These surface winds are locally known as chinook winds and can bring rapid temperature increases of 40-50°F (22-28°C) to areas east of the Rockies that can last for days. 

Montana springs are highly variable and bring dramatic temperature changes. As a whole, Montana’s average spring temperature is 42°F (5.5°C), although western Montana is cooler and warming comes later due to persistence of Pacific maritime air. In contrast, warmer continental air contributes to average temperatures up to 45°F (7.2°C) in spring across central and eastern Montana. 

Elevation and proximity to the Continental Divide strongly influence local temperatures in summer. Valleys and the eastern plains are generally warmer than the higher elevations of the Continental Divide. While summer average temperature across Montana is 64°F (17.8°C), temperatures generally peak in
July and August, with mean daily highs above 90°F (32°C) in the east, as well as in western valleys. 

Fall temperatures in Montana are often highly variable, with an average temperature of 43°F (6.1°C). Days to weeks of warm temperatures are commonly followed by freezing temperatures that bring frosts and snow.

### Precipitation
In general, Montana is a water-limited, semi-arid landscape where precipitation is depended upon heavily by plants and animals alike. Table 2-2 shows the seasonal variation of precipitation across Montana’s seven climate divisions (Figure 2-3) from 1981-2010. Precipitation amounts and form (rain versus snow) vary widely across the state and are strongly influenced by elevation and proximity to the Continental Divide. The average annual precipitation for Montana is 18.7 inches (0.47 m). Western Montana typically receives twice as much precipitation annually as eastern Montana (22-30 inches [0.56-0.76 m] versus 12-14 inches [0.30-0.36 m], respectively). The combination of moisture-rich maritime air from the Pacific in the winter, spring, and fall, and strong convective systems in the summer create a more evenly distributed year-round precipitation pattern in western Montana. In contrast, 65-75% of the annual precipitation occurs in the late spring and summer months for eastern and central Montana, coming from sources in the subtropical Pacific and Gulf of Mexico. 

**ppt table**

## Historical Trends 1979 - Present
We evaluated how temperature and precipitation have historically changed, dating back to mid-20th century. This review of historical trends helps us provide context for future climate change scenarios explored in later sections of this chapter. In addition, evaluating these trends can help us better understand a) how Montanans have previously experienced and responded to changing climate, b) if projections of future change reveal a different climate than we have previously experienced, and c) the potential impacts of that projected change. 

We used standard statistical methods to analyze records of temperature and precipitation spanning two periods: 1950–2015 and 1900–2015.6 The direction (increase or decrease) and significance of trends were generally similar for the two periods. As such, the presentation of trends that follows is confined to the period from 1950–2015. This is widely acknowledged as the benchmark period in climate analysis (Liebmann et al. 2010; IPCC 2013a), a period when our network of meteorological sensors becomes more accurate and sufficiently dense. It also coincides with an upward inflection of the annual average temperature trend for Montana, demarcating a time period with the highest rate of change and likely the strongest anthropogenic signal (NOAAc undated).

Our analysis uses observational data from the US Climate Divisional Database (NOAAc undated) to provide a more complete picture. The data were corrected to remove observational bias (e.g., station relocation, instrumentation changes, and observer practice changes) (Vose et al. 2014). Our approach included combining many stations to provide a more complete picture of historical changes for large regions. In our analyses, we determined if a detectable trend existed for temperature and/or precipitation across the seven climate divisions and/or the entire state.

### Temperature
Table 2-3 shows the decadal rate of change from 1950-2015 for average annual temperatures across Montana. We provide that rate of change both annually and by season for the seven Montana climate divisions depicted in Figure 2-3. We also present the average annual and average seasonal changes statewide and for the US as a whole. To account partially for autocorrelation we considered trends as significant with a conservative p value at p<0.05. Generally, Montana has warmed at a rate faster than the annual national average, as well as within individual seasons.

**Table**

Average annual temperatures increased for the entire state and within all climate divisions (see Figure 2-3). The rate of temperature increase was 0.4°F/decade (0.2°C/decade) across the state, and this rate was relatively constant across all climate divisions (Table 2-3). Similarly, average annual maximum and minimum temperatures increased statewide, and for all seven climate divisions, by 0.3-0.6°F/decade (0.2-0.3°C/decade). Between 1950 and 2015, Montana’s average annual temperature has increased by 2.7°F (1.5°C); annual maximum and minimum temperatures have increased approximately 3.3°F (1.8°C).

> Between 1950 and 2015, average annual temperature increased for the entire state of Montana and within all climate divisions. The state average annual temperature increased 2.7°F (1.5°C); annual maximum and minimum temperatures increased approximately 3.3°F (1.8°C).

**Trend Figure**

### Precipitation
Annual precipitation averaged across the state has not changed significantly since 1950. Some change, however, has occurred within different climate divisions and for different seasons as shown in Table 2-4. We found no significant changes in summer and fall precipitation between 1950-2015 for any climate division. Seasonally, the largest changes—declines—in precipitation (rain and snow combined) have occurred during winter months (Table 2-4). We used a smaller p value (<0.05) to determine statistical significance of trends and to account for potential autocorrelation of time series data. Our analysis suggests that an increase in the number of El Niño events since 1950 has contributed to drier winters and decreased precipitation for Montana’s northwestern, north central, and central climate divisions (see Teleconnections section for more on the El Niño Southern Oscillation). In the eastern portions of the state significant increases in precipitation have occurred during the spring months (Table 2-4).

**table**

### Extreme aspects of Montana’s climate
Along with analyzing historical trends in temperature and precipitation, we performed an analysis of changes in extreme climate events since the middle of last century. Two examples of climate extremes include periods of intense warm or cool temperatures and significant wet or dry spells across seasons. Because these events affect every aspect of our society, decision makers and stakeholders are increasingly in need of historical evaluations of extreme events and how they are changing from seasons to centuries. The coldest temperature ever observed in the conterminous US was -70°F (-57°C) at Rogers Pass outside of Helena on January 20, 1954 (see sidebar). Since 1950, however, our analysis shows the average winter temperature has increased by 0.4°F/decade (0.2°C/decade) across the state, with an overall average winter temperature increase of 3.6°F (2.0°C). Average spring temperatures have increased by 2.6°F (1.4°C) during the same period, and average summer temperatures have risen by 2.0°F (1.1°C). Montana’s fall average temperatures have increased by 1.6°F (0.9°C) since 1950.

We performed our analysis of climate extremes using the CLIMDEX project (CLIMDEX undated), which provides a collection of global and regional climate data from multiple sources. CLIMDEX is developed and maintained by researchers at the Climate Change Research Centre and the University of New South Wales, in collaboration with the University of Melbourne, Climate Research Division of Environment Canada, and NOAA’s National Centers for Environmental Information. The CLIMDEX project aims to produce a global dataset of standardized indices representing the extreme aspects of climate. Particular attention was placed on the changes in variables such as consecutive dry days, days of heavy precipitation, growing season length, frost days, number of cool days and nights, and the number of warm days and nights. Extreme precipitation events across the United States have increased in both intensity and frequency since 1901 (NCA 2014), including across both the High Plains and the northwestern US (many states combined), where studies have shown an increase in the number of days with extreme precipitation (NCA 2014). However, for our analysis at the state level we found no evidence of changes in extreme precipitation so it is not a variable of focus. Here, we report those variables that did change significantly (p<0.05) for Montana and, for perspective, the climate normals for these extremes for the periods 1951–1980 and from 1981-2010 (Table 2-5).

**extremes table**

The annual number of cool days and the number of days with frost are decreasing across Montana. We use the CLIMDEX definition of cool days as the percentage of days when maximum temperature is lower than 10% of the historical observations. Coincident with warming temperatures, the number of cool days each year during the period from 1951–2010 has decreased by 13.3 days. Along with this trend, the number of days in which the minimum temperatures are below 32°F (0°C; i.e. frost days) has decreased by 12 days during this time period. These trends have contributed to an overall increase in the growing season length of 12 days between 1951 and 2010. In addition, the number of warm days, where maximum temperature exceeds 90°F (32°C) based on historical conditions, has increased by 11 days over this period. At a sub-annual level, monthly maximum and minimum temperatures have also changed. These are defined as the monthly maximum (minimum) value of daily maximum (minimum) temperatures. Monthly minimum values of daily minimum temperatures have increased by 5°F (2.8°C) from the period 1951–2010. Over the same time period, monthly minimum values of daily maximum temperatures have increased by 1.1°F (0.6°C).

There has been an increase in the number of warm nights and a related decrease in the number of cool nights across Montana. We use the CLIMDEX definition of warm nights (and cool nights) as the number of days when minimum temperature is higher (lower) than a specified maximum (minimum) threshold defined by historical conditions. The number of warm nights has increased by 11 days from 1951 to 2010. The number of cool nights has decreased by 12 days over this same period. These trends are in agreement with observations across many portions of the continental US (Davy and Esau 2016).

> Between 1951 and 2010, the growing season in Montana increased 12 days.

::: {.callout-note icon=false}
### Drought {#drought-callout}

Drought is a recurrent climate event that may vary in intensity and persistence by region. Drought can have broad and potentially devastating environmental and economic impacts (Wilhite 2000); thus, it is a topic of ongoing, statewide concern. 

Through time, Montana’s people, agriculture, and industry, like its ecosystems, have evolved with drought. Today, many entities across the state address drought, including private and non-profit organizations, state and federal agencies, and landowners, as well as unique watershed partnerships. 

Drought is a complex phenomenon driven by both climate, but also affected by human-related factors (e.g., land use, water use). Although the definition of drought varies in different operational contexts, most definitions include several interrelated components, including: 

- meteorological drought, defined as a deficit in precipitation and above average evapotranspiration that lead to increased aridity;

- hydrological drought, characterized by reduced water levels in streams, lakes, and aquifers following prolonged periods of meteorological drought;

- ecological drought, defined as a prolonged period over which an ecosystem’s demand for water exceeds the supply (the resulting water deficit, or shortage, creates multiple stresses within and across ecosystems); and

- agricultural drought, commonly understood as a deficit in soil moisture and water supply that lead to decreased productivity (in this assessment, we will treat this form of drought as an important component of ecological drought). 

While the subsequent chapters dealing with water, agriculture, and forests treat the subject of drought differently, each describes drought within the context of one or more of the four definitions described above.
:::
