# Overview {.unnumbered}

Understanding current climate change and projecting future climate trends are of vital importance–both for our economy and our well-being. It is our goal to provide science-based information that serves as a resource for *Montanans* who are interested in understanding *Montana*’s climate and its impacts on water, agricultural lands and forests. To provide this understanding, we can learn from past climate trends. However, knowledge of the past is only partially sufficient in preparing for a future defined by unprecedented levels of greenhouse gases in the atmosphere. Therefore, we also provide projections of change into the future using today’s best scientific information and modeling techniques.

## Key Messages
Annual average temperatures, including daily minimums, maximums, and averages, have risen across the state between 1950 and 2015. The increases range between **2.0-3.0°F (1.1-1.7°C)** during this period.

Winter and spring in Montana have experienced the most warming. Average temperatures during these seasons have risen by **3.9°F (2.2°C)** between 1950 and 2015.

Montana’s growing season length is increasing due to the earlier onset of spring and more extended summers; we are also experiencing more warm days and fewer cool nights. From **1951-2010**, the growing season increased by **12** days. In addition, the annual number of warm days has increased by **2.0%** and the annual number of cool nights has decreased by **4.6%** over this period.

Despite no historical changes in average annual precipitation between 1950 and 2015, there have been changes in average seasonal precipitation over the same period. Average winter precipitation has decreased by **0.9 inches (2.3 cm)**, which can mostly be attributed to natural variability and an increase in El Niño events, especially in the **western and central parts of the state**. A significant increase in spring precipitation **(1.3-2.0 inches [3.3-5.1 cm])** has also occurred during this period for the **eastern portion** of the state.

The state of Montana is projected to continue to warm in all geographic locations, seasons, and under all emission scenarios throughout the 21st century. By mid century, Montana temperatures are projected to increase by approximately **4.5-6.0°F (2.5-3.3°C)** depending on the emission scenario. By the end-of-century, Montana temperatures are projected to increase **5.6-9.8°F (3.1-5.4°C)** depending on the emission scenario. These state-level changes are larger than the average changes projected globally and nationally.

The number of days in a year when daily temperature exceeds 90°F (32°C) and the number of frost-free days are expected to increase across the state and in both emission scenarios studied. Increases in the number of days above 90°F (32°C) are expected to be greatest in the **eastern** part of the state. Increases in the number of frost-free days are expected to be greatest in the **western** part of the state.

Across the state, precipitation is projected to increase in **winter, spring, and fall;** precipitation is projected to decrease in *summer.* The largest increases are expected to occur during *spring* in the *southern* part of the state. The largest decreases are expected to occur during *summer* in the *central* and *southern* parts of the state. 

## Climate Change Defined
The US Global Change Research Program (USGCRP undated) defines climate change as follows:

> “Changes in average weather conditions that persist over multiple decades or longer. Climate change encompasses both increases and decreases in temperature, as well as shifts in precipitation, changing risk of certain types of severe weather events, and changes to other features of the climate system.”

## Outline
This document focuses on three areas:

1. providing a baseline summary of climate and climate change for Montana—with a focus on changes in temperature, precipitation, and extreme events—including reviewing the fundamentals of climate change science;

2. reviewing historical trends in Montana’s climate, and what those trends reveal about how our climate has changed in the past century, changes that are potentially attributable to world-wide increases in greenhouse gases; and

3. considering what today’s best available climate models project regarding Montana’s future, and how certain we can be in those projections.

This chapter serves as a foundation for the Montana Climate Assessment, providing information on present-day climate and climate terminology, past climate trends, and future climate projections. This foundation then serves as the basis for analyzing three key sectors of Montana—water, forests, and agriculture—considered in the other chapters of this assessment. In the sections below, we introduce the climate science and discuss important fundamental processes that determine whether climate remains constant or changes.
