---
title: "Rerunning the Montana Climate Assessment with CMIP6 Data"
---

```{r include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  eval = FALSE
)
```

```{r setup}
library(magrittr)
library(terra)
library(sf)
library(ggplot2)

mt_state_plane <- 'PROJCS["NAD_1983_HARN_StatePlane_Montana_FIPS_2500 (deprecated)",
    GEOGCS["NAD83(HARN)",
        DATUM["NAD83_High_Accuracy_Reference_Network",
            SPHEROID["GRS 1980",6378137,298.257222101,
                AUTHORITY["EPSG","7019"]],
            AUTHORITY["EPSG","6152"]],
        PRIMEM["Greenwich",0,
            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,
            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4152"]],
    PROJECTION["Lambert_Conformal_Conic_2SP"],
    PARAMETER["latitude_of_origin",44.25],
    PARAMETER["central_meridian",-109.5],
    PARAMETER["standard_parallel_1",45],
    PARAMETER["standard_parallel_2",49],
    PARAMETER["false_easting",600000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["ESRI","102300"]]'

mt <- sf::read_sf("https://data.climate.umt.edu/mca/fgb/mt.fgb") %>% 
  sf::st_transform(mt_state_plane)

counties <- sf::read_sf(
  "https://data.climate.umt.edu/mca/fgb/mt_counties.fgb"
) %>%
  sf::st_transform(mt_state_plane)

climdiv <- sf::read_sf(
  "https://data.climate.umt.edu/mca/fgb/mt_climdiv.fgb"
) %>%
  sf::st_transform(mt_state_plane)%>% 
  dplyr::mutate(NAME = tolower(NAME) %>% tools::toTitleCase())


reference_period <- c(1981, 2010)
mid_century <- c(2040, 2069)
end_century <- c(2070, 2099)
```

```{r to_shp} 
to_shp <- function(x, mt) {
  
  tmp <- x %>%
    terra::project(mt_state_plane) %>%
    # terra::mask(mt %>% terra::vect(), touches=F) %>%
    raster::stack() %>%
    # mco_mask(mask = mt) %>%
    spex::qm_rasterToPolygons(na.rm = T) %>%
    tidyr::pivot_longer(-geometry, names_to = "time")  %>%
    sf::`st_crs<-`(mt_state_plane)
  
  mt_use <- sf::st_transform(mt, sf::st_crs(tmp)) %>% 
    dplyr::select(geometry)
  
  sf::st_intersection(tmp, mt_use)
}
```

```{r summary_functions}
time_avg <- function(
    fs, reference_period, period="annual", fun="mean", transform = NULL, remote = FALSE
) {
  
  checkmate::assert_choice(period, c("annual", "seasonal", "monthly"))
  
  read_func <- ifelse(remote, normals::read_from_server, terra::rast)
  print(fs[1])
  stk <- read_func(fs) %>%  
    terra::tapp(index="days", fun="mean")
  
  times <- tibble::tibble(
    date = names(stk) %>% 
      stringr::str_replace("X", "") %>% 
      lubridate::as_date()
  ) %>% 
    dplyr::mutate(
      season = dplyr::case_when(
        lubridate::month(date) %in% c(12, 1, 2) ~ "Winter", # 1=winter
        lubridate::month(date) %in% c(3, 4, 5) ~ "Spring", # 2=spring
        lubridate::month(date) %in% c(6, 7, 8) ~ "Summer", # 3=summer
        lubridate::month(date) %in% c(9, 10, 11) ~ "Fall" # 4=fall
      ), 
      idx = 1:dplyr::n(),
      month = lubridate::month(date)
    ) %>% 
    dplyr::rowwise() %>% 
    dplyr::mutate(
      year = ifelse(
        (season == "Winter") && (lubridate::month(date)) == 12, 
        lubridate::year(date) + 1,
        lubridate::year(date)
      )
    ) %>%
    dplyr::group_by(year, season) %>% 
    dplyr::mutate(
      yearly_grp = dplyr::cur_group_id(),
      group_count = dplyr::n()
    ) %>% 
    dplyr::filter(
      year %in% reference_period[1]:reference_period[2],
    ) %>% 
    dplyr::mutate(
      yearly_grp = glue::glue("{season} {year}")
    )
  
  if (nrow(times) == 0) {
    return(NULL)
  }


  if (period == "annual"){
    r_filtered <- terra::subset(stk, times$idx) 

    out <- terra::tapp(
      r_filtered, index = times$year, fun = fun
    )
  } else if (period == "seasonal") {
    
    time_tmp <- dplyr::filter(times, group_count == 3)
    r_filtered <- terra::subset(stk, time_tmp$idx) 

    out <- terra::tapp(
      r_filtered, index = time_tmp$yearly_grp, fun = fun
    )  
  } else {
    r_filtered <- terra::subset(stk, times$idx) 

    out <- r_filtered
  }
  
  if (!is.null(transform)) {
    return(transform(out))
  }
  return(out)
}

timeseries_to_summary <- function(r, period) {
  
  if (is.null(r)) {
    return(NULL)
  }
  checkmate::assert_choice(period, c("annual", "seasonal", "monthly"))
  
  meta <- tibble::tibble(name = names(r))
  
  if (period == "annual") {
    grp <- rep("Annual", terra::nlyr(r))
  } else if (period == "seasonal") {
    grp <- meta %>% 
      tidyr::separate(name, c("season", "year")) %$% 
      # dplyr::mutate(season = factor(season, levels = c("Winter", "Spring", "Summer", "Fall"))) %$%
      season
  } else {
    grp <- meta %>% 
      dplyr::transmute(
        date = lubridate::as_date(name, format="X%Y.%m.%d"),
        month = month.name[lubridate::month(date)]
      ) %$%
      month
  }
  
  terra::tapp(
    r, index = grp, fun = "mean"
  )
}

trend_func <- function(ys, threshold = 0.05) {
  
  xs <- 1:length(ys)
  mod <- lm(ys ~ xs)
  coeffs <- coef(mod)
  
  meta <- summary(mod)
  if (meta$coefficients[,4][2] > threshold) {
    return(0)
  }
  coeffs[2]
}



tas_tsfm <- function(x) (x - 273.15) * 1.8 + 32
pr_tsfm <- function(x) x/25.4

```

```{r preprocess_cmip, warning=FALSE}
scenarios <- "historical|ssp126|ssp245|ssp370|ssp585"
ssp_colors <- c("ssp126"="#7570b3", "ssp245"="#1b9e77", "ssp370"="#e7298a", "ssp585"="#d95f02")

f_list <- RCurl::getURL(
  "https://data.climate.umt.edu/mca/cmip/",
  ftp.use.epsv = TRUE,
  dirlistonly = FALSE
) %>% 
  XML::getHTMLLinks() %>% 
  grep(".tif", ., value = T) %>%
  grep(".json", ., value = T, invert = T) %>%
  grep(scenarios, ., value = T)

cmip_files <- file.path(
  "https://data.climate.umt.edu/mca/cmip",
  basename(f_list)
)
```

```{r table2.1}
dat <- c(
  "https://data.climate.umt.edu/mca/gridmet/tmmn.tif", 
  "https://data.climate.umt.edu/mca/gridmet/tmmx.tif"
) %>% 
  purrr::map(function(x) {
    time_avg(
      x,
      c(1991, 2020),
      "seasonal", 
      "mean", 
      tas_tsfm,
      TRUE
    ) %>% 
      timeseries_to_summary("seasonal") # %>%
      # spat_summary(shp = climdiv, "NAME", fun="mean") %>% 
      # dplyr::select(div=NAME, timescale, value) %>% 
      # dplyr::mutate(
      #   variable = basename(tools::file_path_sans_ext(x))
      # )
  }) %>%
  {(.[[1]] + .[[2]])/2} %>% 
  to_shp(mt=mt)
  # dplyr::bind_rows() %>% 
  # tidyr::pivot_wider(names_from = "variable", values_from = "value") %>% 
  # dplyr::mutate(
  #   tavg = (tmmn + tmmx)/2,
  # ) 

fig <- dat %>% 
  # to_shp(mt=mt) %>%
  dplyr::mutate(
    time = dplyr::case_when(
      time == "Winter" ~ "Winter (DJF)",
      time == "Spring" ~ "Spring (MAM)",
      time == "Summer" ~ "Summer (JJA)",
      time == "Fall" ~ "Fall (SON)"
    ),
    time = factor(time, levels = c("Winter (DJF)", "Spring (MAM)", "Summer (JJA)", "Fall (SON)"))
  ) %>% 
  dplyr::group_by(time) %>% 
  dplyr::group_split() %>%
  purrr::map(function(x) {
    labs <- seq(min(x$value), max(x$value), length.out = 6) %>% 
          round(1) 
    
    ggplot(data = x) + 
      geom_sf(aes(fill=value), color = NA) + 
      geom_sf(aes(), data = climdiv, fill=NA) +
      facet_wrap(~time) +
      scale_fill_gradientn(
        colors = viridis::viridis_pal(option="plasma")(9), 
        limits = c(min(labs)-1, max(labs)+1),
        breaks = labs,
        labels = format(labs, nsmall=1)
      ) +
      # scale_fill_viridis_c() + 
      # scale_fill_gradient2(
      #   low = pal[1], mid = pal[2], high =  pal[3],
      #   midpoint = midpoint
      # ) +
      theme_minimal() +
      theme(
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        legend.key.height = unit(0.05, "npc"),
        strip.text.x = element_text(size = 11, face="bold")
      ) +
      labs(y="", x = "", fill = "")
  }) %>%
  {cowplot::plot_grid(.[[1]], .[[2]], .[[3]], .[[4]], nrow=2)}

title <- cowplot::ggdraw() + 
  cowplot::draw_label(
    "Seasonal Average Temperature (°F) Across Montana (1991 - 2020)",
    fontface = 'bold',
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 0)
  )
fig <- cowplot::plot_grid(
  title, fig,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

png("./figures/historical_tavg.png", width = 10, height=6, units="in", res=320)
print(fig)
dev.off()

# annual <- tidyr::pivot_longer(dat, c(tmmn, tmmx, tavg)) %>% 
#   dplyr::group_by(div, name) %>% 
#   dplyr::summarise(Annual = mean(value), .groups="drop") %>% 
#   tidyr::pivot_wider(names_from = name, values_from = Annual) %>% 
#   dplyr::mutate(timescale = "Annual")
# 
# dplyr::bind_rows(dat, annual) %>% 
#   dplyr::transmute(
#     `Climate Division` = tools::toTitleCase(tolower(div)), 
#     timescale = factor(timescale, levels = c("Annual", "Winter", "Spring", "Summer", "Fall")),
#     meta = paste(round(tmmn, 1), round(tavg, 1), round(tmmx, 1), sep = " / ")
#   ) %>%
#   tidyr::pivot_wider(names_from = 'timescale', values_from='meta', names_sort = T) 
  # knitr::kable(
  #   caption = "Table 1: Average temperatures (°F) and Precipitation (in) across Montana from 1991-2020."
  # )
```

```{r table2.2}
dat <- time_avg(
  "https://data.climate.umt.edu/mca/gridmet/pr.tif",
  c(1991, 2020),
  "seasonal", 
  "sum", 
  pr_tsfm,
  TRUE
) %>% 
  timeseries_to_summary("seasonal") 
  # spat_summary(shp = climdiv, "NAME", fun="mean") %>% 
  # dplyr::select(div=NAME, timescale, value) 

fig <- dat %>% 
  to_shp(mt=mt) %>%
  dplyr::mutate(
    time = dplyr::case_when(
      time == "Winter" ~ "Winter (DJF)",
      time == "Spring" ~ "Spring (MAM)",
      time == "Summer" ~ "Summer (JJA)",
      time == "Fall" ~ "Fall (SON)"
    ),
    time = factor(time, levels = c("Winter (DJF)", "Spring (MAM)", "Summer (JJA)", "Fall (SON)"))
  ) %>%
  dplyr::group_by(time) %>% 
  dplyr::group_split() %>%
  purrr::map(function(x) {
    labs <- seq(min(x$value), max(x$value), length.out = 6) %>% 
          round(1) 
    
    ggplot(data = x) + 
      geom_sf(aes(fill=value), color = NA) + 
      geom_sf(aes(), data = climdiv, fill=NA) +
      facet_wrap(~time) +
      scale_fill_gradientn(
        colors = viridis::viridis_pal()(9), 
        limits = c(min(labs)-1, max(labs)+1),
        breaks = labs,
        labels = labs
      ) +
      # scale_fill_viridis_c() + 
      # scale_fill_gradient2(
      #   low = pal[1], mid = pal[2], high =  pal[3],
      #   midpoint = midpoint
      # ) +
      theme_minimal() +
      theme(
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        plot.title = element_text(hjust = 0.5),
        legend.key.height = unit(0.05, "npc"),
        strip.text.x = element_text(size = 11, face="bold")
      ) +
      labs(y="", x = "", fill = "")
  }) %>%
  {cowplot::plot_grid(.[[1]], .[[2]], .[[3]], .[[4]], nrow=2)}

title <- cowplot::ggdraw() + 
  cowplot::draw_label(
    "Seasonal Precipitation (in.) Totals Across Montana (1991 - 2020)",
    fontface = 'bold',
  ) +
  theme(
    # add margin on the left of the drawing canvas,
    # so title is aligned with left edge of first plot
    plot.margin = margin(0, 0, 0, 0)
  )
fig <- cowplot::plot_grid(
  title, fig,
  ncol = 1,
  # rel_heights values control vertical title margins
  rel_heights = c(0.1, 1)
)

png("./figures/historical_pr.png", width = 10, height=6, units="in", res=320)
print(fig)
dev.off()
# dat %<>% 
#   spat_summary(shp = climdiv, "NAME", fun="mean") %>%
#   dplyr::select(div=NAME, timescale, value)
# 
# annual <- dplyr::group_by(dat, div) %>% 
#   dplyr::summarise(value = sum(value), .groups="drop") %>% 
#   dplyr::mutate(timescale = "Annual")
# 
# dplyr::bind_rows(dat, annual) %>% 
#   dplyr::transmute(
#     `Climate Division` = tools::toTitleCase(tolower(div)), 
#     timescale = factor(timescale, levels = c("Annual", "Winter", "Spring", "Summer", "Fall")),
#     value = value
#   ) %>%
#   tidyr::pivot_wider(names_from = 'timescale', values_from='value', names_sort = T) 
```

```{r table 2.3}
dat <- c(
  "https://data.climate.umt.edu/mca/gridmet/tmmn.tif", 
  "https://data.climate.umt.edu/mca/gridmet/tmmx.tif"
) %>% 
  purrr::map(function(x) {
    time_avg(
      x,
      c(1979, 2020),
      "seasonal", 
      "mean", 
      tas_tsfm,
      TRUE
    ) %>% 
      normals::spat_summary(
        shp = climdiv, attr_id = "NAME", fun="mean"
      ) %>% 
      dplyr::select(div=NAME, timescale, value) %>% 
      dplyr::mutate(
        variable = basename(tools::file_path_sans_ext(x))
      )
  }) %>% 
  dplyr::bind_rows()


# # Just a check to look at the trends. 
# dat %>% 
#   tidyr::separate(timescale, c("season", "year")) %>%
#   dplyr::mutate(year = as.numeric(year)) %>% 
#   dplyr::filter(variable == 'tmmn') %>%
#   ggplot(aes(x=year, y=value)) + 
#     geom_point() +
#     facet_wrap(season~div, scales="free_y") +
#     geom_smooth(method='lm')

tidyr::separate(dat, timescale, c("season", "year")) %>%
  dplyr::group_by(div, year, variable) %>%
  dplyr::mutate(Annual = mean(value)) %>% 
  dplyr::ungroup() %>% 
  tidyr::pivot_wider(names_from = season, values_from = value) %>% 
  tidyr::pivot_longer(-c(div, year, variable), names_to = "season") %>%
  tidyr::pivot_wider(names_from = variable, values_from = value) %>% 
  dplyr::mutate(tavg = (tmmn + tmmx)/2) %>% 
  tidyr::pivot_longer(-c(div, year, season)) %>%
  dplyr::group_by(div, season, name) %>% 
  dplyr::summarise(trend = trend_func(value, threshold=0.05)) %>%
  dplyr::mutate(trend = round(trend, 3)) %>% 
  tidyr::pivot_wider(names_from = name, values_from = trend) %>% 
  dplyr::ungroup() %>% 
  dplyr::transmute(
    `Climate Division` = tools::toTitleCase(tolower(div)), 
    timescale = factor(season, levels = c("Annual", "Winter", "Spring", "Summer", "Fall")),
    meta = paste(tmmn, tavg, tmmx, sep = " / ")
  ) %>%
  tidyr::pivot_wider(names_from = 'timescale', values_from='meta', names_sort = T) 
```

```{r fig2.4, message=FALSE, warning=FALSE}
dat <- c(
  "https://data.climate.umt.edu/mca/gridmet/tmmn.tif", 
  "https://data.climate.umt.edu/mca/gridmet/tmmx.tif"
) %>% 
  purrr::map(function(x) {
    time_avg(
      x,
      c(1979, 2020),
      "annual", 
      "mean", 
      tas_tsfm,
      TRUE
    ) %>% 
      normals::spat_summary(
        shp = climdiv, attr_id = "NAME", fun="mean"
      ) %>% 
      dplyr::select(div=NAME, timescale, value) %>% 
      dplyr::mutate(
        variable = basename(tools::file_path_sans_ext(x))
      )
  }) %>% 
  dplyr::bind_rows()

fig <- dat %>% 
  dplyr::mutate(
    div = tools::toTitleCase(tolower(div)),
    div = climdiv_to_factor(div),
    year = timescale %>% 
      stringr::str_replace("X", "") %>% 
      as.numeric()
  ) %>% 
  dplyr::group_by(div, year) %>% 
  dplyr::summarise(value = mean(value)) %>%
  ggplot(aes(x=year, y=value)) +
    geom_line() + 
    geom_smooth(method = "lm") + 
    facet_wrap(~div, nrow=7, scales = "free_y") + 
    theme_bw() + 
    labs(title = "Temperature Trend Across Climate Divisions (1979 - 2020)", y = "Mean Annual Temperature (°F)", y="") +
    theme(
      plot.title = element_text(hjust=0.5, face="bold")
    )

ggsave(glue::glue("./figures/hist_trends.png"), fig, width=10, height=8)
```

```{r table2.4}
dat <- time_avg(
  "https://data.climate.umt.edu/mca/gridmet/pr.tif",
  c(1979, 2020),
  "seasonal", 
  "sum", 
  pr_tsfm,
  TRUE
) %>% 
  normals::spat_summary(
    shp = climdiv, attr_id = "NAME", fun="mean"
  ) %>% 
  dplyr::select(div=NAME, timescale, value)

# # Just a check to look at the trends. 
# dat %>% 
#   tidyr::separate(timescale, c("season", "year")) %>%
#   dplyr::mutate(year = as.numeric(year)) %>% 
#   dplyr::filter(variable == 'tmmn') %>%
#   ggplot(aes(x=year, y=value)) + 
#     geom_point() +
#     facet_wrap(season~div, scales="free_y") +
#     geom_smooth(method='lm')

tidyr::separate(dat, timescale, c("season", "year")) %>%
  dplyr::group_by(div, year) %>%
  dplyr::mutate(Annual = sum(value)) %>% 
  dplyr::ungroup() %>% 
  tidyr::pivot_wider(names_from = season, values_from = value) %>% 
  tidyr::pivot_longer(-c(div, year), names_to = "season") %>%
  dplyr::group_by(div, season) %>% 
  dplyr::summarise(trend = trend_func(value, threshold=0.05)) %>%
  dplyr::mutate(trend = round(trend, 3)) %>% 
  dplyr::ungroup() %>% 
  dplyr::transmute(
    `Climate Division` = tools::toTitleCase(tolower(div)), 
    timescale = factor(season, levels = c("Annual", "Winter", "Spring", "Summer", "Fall")),
    meta = trend
  ) %>%
  tidyr::pivot_wider(names_from = timescale, values_from = meta) 
```

```{r future_comparison_funcs, message=FALSE, warning=FALSE}
filter_years <- function(r, start, end) {
  years <- which(names(r) %in% paste0("X", start:end))
  if (length(years) == 0) {
    return(NA)
  }
  terra::subset(r, years) %>%
    terra::app(fun="mean") 
}

summarize_yearmonths <- function(r, start, end) {
  
  yearmons <- tidyr::crossing(
    a="X", b=start:end, c=stringr::str_pad(1:12, 2, "left", "0")
  ) %>% 
    dplyr::mutate(out = glue::glue("{a}{b}{c}")) %$%
    as.character(out)
  
  yearmons_idx <- which(names(r) %in% yearmons)
  if (length(yearmons_idx) == 0) {
    return(NA)
  }
  
  r <- terra::subset(r, yearmons_idx) 
  terra::time(r) <- lubridate::as_date(paste0(yearmons, "01"), format = "X%Y%m%d")
  r <- terra::tapp(r, fun="mean", index = "months")
  names(r) <- month.name
  return(r)
}

join_historical <- function(dat) {
  dat %>%  
    dplyr::select(model, scenario, hist, mid_century, end_century) %>%
    dplyr::left_join(
      dplyr::filter(., scenario == "historical") %>%
        dplyr::select(model, historical=hist),
      by = "model"
    ) %>%
    dplyr::select(-hist) %>%
    dplyr::filter(scenario != "historical") %>%
    tidyr::pivot_longer(
      c("mid_century", "end_century")
    ) 
}

read_and_tapp <- function(pattern, files, fun, idx, tsfm=NULL) {
  out <- grep(pattern, files, value = T) %>% 
    purrr::map(function(x) {
      
      r <- normals::read_from_server(x) %>% 
        terra::tapp(index = idx, fun = fun) 
      tibble::tibble(
        f = tools::file_path_sans_ext(x) %>% basename(),
        r = list(r)
      )
    }) %>%
    dplyr::bind_rows() %>%
    tidyr::separate(f, c("model", "scenario", "run", "variable"), sep = "_")
  
  if (!is.null(tsfm)) {
    out <- 
      dplyr::rowwise(out) %>% 
      dplyr::mutate(r = list(tsfm(r))) %>% 
      dplyr::ungroup()
  }
  return(out) 
}

climdiv_to_factor <- function(x) {
  factor(x, levels = c("Western", "Southwestern", "North Central", "Central", "South Central", "Northeastern", "Southeastern"))
}

clean_factor_period <- function(x) {
  x %>% 
    stringr::str_replace("mid_", "Mid ") %>% 
    stringr::str_replace("end_", "End of ") %>% 
    tools::toTitleCase() %>%
    factor(levels = c("Mid Century", "End of Century"))
}

make_boxplot_data <- function(files, pattern, shp, attr_id, fun, idx="years", tsfm = NULL) {

  read_and_tapp(files = files, pattern = pattern, fun = fun, idx = idx, tsfm = tsfm)  %>%
    dplyr::rowwise() %>%
    dplyr::mutate(
      hist = list(filter_years(r, 1981, 2010)),
      mid_century = list(filter_years(r, 2040, 2069)),
      end_century = list(filter_years(r, 2070, 2099))
    ) %>% 
    join_historical() %>%
    dplyr::rowwise() %>%
    dplyr::transmute(
      scenario = scenario,
      period = name,
      diff = list(round(value - historical)),
      model=model
    )  %>%
    dplyr::mutate(diff = list(normals::spat_summary(diff, shp, attr_id, fun="mean"))) %>% 
    tidyr::unnest(diff) %>%
    dplyr::select(scenario, period, area=dplyr::all_of(attr_id), diff=value) %>%
    dplyr::mutate(
      period = clean_factor_period(period)
    )
}

make_boxplot_plot <- function(dat, ylab, title) {

  ggplot(dat, aes(x=scenario, y=diff, fill=scenario)) +
    geom_violin(alpha=0.8) +
    facet_grid(rows = dplyr::vars(period), cols=dplyr::vars(area)) +
    theme_bw() +
    scale_fill_manual(values = ssp_colors) +
    theme(
      axis.text.x = element_text(angle = 45, vjust = 0.5),
      plot.title = element_text(hjust = 0.5)
    ) +
    labs(y=ylab, x = "", fill = "Scenario", title = title) + 
    geom_hline(yintercept = 0)
}

make_map_data <- function(files, pattern, fun, shp, attr_id, tsfm = NULL) {
  read_and_tapp(files = files, pattern = pattern, fun = fun, idx = "years", tsfm = tsfm)  %>%
    dplyr::rowwise() %>%
    dplyr::mutate(
      hist = list(filter_years(r, 1981, 2010)),
      mid_century = list(filter_years(r, 2040, 2069)),
      end_century = list(filter_years(r, 2070, 2099))
    ) %>%
    join_historical() %>%
    dplyr::rowwise() %>%
    dplyr::transmute(
      scenario = scenario,
      period = name,
      diff = list(round(value - historical)),
      model=model
    ) %>%
    dplyr::group_by(scenario, period) %>%
    dplyr::summarise(
      diff = list(terra::app(terra::rast(diff), fun="mean"))
    ) %>%
    dplyr::rowwise() %>% 
    dplyr::mutate(
      diff = list(to_shp(diff, mt=mt))
    ) %>%
    dplyr::select(scenario, period, diff) %>% 
    tidyr::unnest(diff) %>%
    sf::st_as_sf() %>%
    dplyr::mutate(
      period = clean_factor_period(period)
    )

}

make_map_plot <- function(dat, hot=TRUE) {

  diverging <- any(dat$value < 0)
  if (hot && diverging) {
    pal <-  c('#fc8d59','#ffffbf','#91bfdb')
  } else if (hot && !diverging) {
    pal <- c('#fee8c8','#fdbb84','#e34a33')
  } else if (!hot && diverging) {
    pal <- c('#d8b365','#f5f5f5','#5ab4ac')
  } else {
    pal <- c('#ece7f2','#a6bddb','#2b8cbe')
  }

  midpoint <- ifelse(diverging, 0, mean(dat$value))

  fig <- ggplot(dat) +
    geom_sf(aes(fill=value), color=NA) +
    geom_sf(aes(), data = climdiv, fill=NA) +
    facet_grid(rows = vars(scenario), cols = vars(period)) +
    scale_fill_gradient2(
      low = pal[1], mid = pal[2], high =  pal[3],
      midpoint = midpoint
    ) +
    theme_bw() +
    theme(
      axis.text.x = element_text(angle = 45, vjust = 0.5),
      plot.title = element_text(hjust = 0.5)
    ) +
    labs(y="", x = "", fill = "")
  
  return(fig)
}

apply_map_by_scenario <- function(dat, hot, title_txt) {
  plt <- dat %>% 
    dplyr::group_by(scenario) %>% 
    dplyr::group_split() %>% 
    lapply(make_map_plot, hot = hot) %>% 
    {cowplot::plot_grid(.[[1]], .[[2]], nrow=2)} 
  
  title <- cowplot::ggdraw() + 
    cowplot::draw_label(
      title_txt,
      fontface = 'bold',
    ) +
    theme(
      # add margin on the left of the drawing canvas,
      # so title is aligned with left edge of first plot
      plot.margin = margin(0, 0, 0, 0)
    )
  cowplot::plot_grid(
    title, plt,
    ncol = 1,
    # rel_heights values control vertical title margins
    rel_heights = c(0.1, 1)
  )
}

make_heatmap_data <- function(files, pattern, fun, shp, attr_id, tsfm = NULL) {
  
   read_and_tapp(
    files = files, pattern = pattern, fun = fun, idx = "yearmonths", tsfm = tsfm
  ) %>%
    dplyr::rowwise() %>%
    dplyr::mutate(
      hist = list(summarize_yearmonths(r, 1981, 2010)),
      mid_century = list(summarize_yearmonths(r, 2040, 2069)),
      end_century = list(summarize_yearmonths(r, 2070, 2099))
    ) %>%
    join_historical() %>%
    dplyr::rowwise() %>%
    dplyr::mutate(diff = list(value - historical)) %>%
    dplyr::group_by(scenario, name) %>%
    dplyr::summarise(
      diff = list(terra::tapp(terra::rast(diff), index = month.name, fun = "mean")),
      .groups = "drop"
    ) %>%
    dplyr::rowwise() %>%
    dplyr::mutate(
      diff = list(normals::spat_summary(diff, shp, attr_id, "month", "mean"))
    ) %>%
    tidyr::unnest(diff) %>%
    dplyr::select(scenario, period=name, area=dplyr::all_of(attr_id), month, diff=value) %>%
    dplyr::mutate(
      period = clean_factor_period(period),
      month = factor(month, levels=month.name)
    )
}

make_heatmap_plot <- function(dat, hot = TRUE) {
  
  diverging <- any(dat$diff < 0)
  if (hot && diverging) {
    pal <-  c('#fc8d59','#ffffbf','#91bfdb')
  } else if (hot && !diverging) {
    pal <- c('#fee8c8','#fdbb84','#e34a33')
  } else if (!hot && diverging) {
    pal <- c('#d8b365','#f5f5f5','#5ab4ac')
  } else {
    pal <- c('#ece7f2','#a6bddb','#2b8cbe')
  }
  
  midpoint <- ifelse(diverging, 0, mean(dat$diff))
  
  ggplot(dat) +
    geom_tile(aes(x=month, y=area, fill=diff), color="black") + 
    scale_fill_gradient2(
      low = pal[1], mid = pal[2], high =  pal[3],
      midpoint = midpoint
    ) +
    facet_grid(rows = vars(scenario), cols = vars(period)) +
    theme_bw() + 
    labs(x="", y = "", fill = "") +
    theme(axis.text.x = element_text(angle = 45, vjust = 0.5)) 
}

apply_heatmap_by_scenario <- function(dat, hot, title_txt) {
  plt <- dat %>% 
    dplyr::group_by(scenario) %>% 
    dplyr::group_split() %>% 
    lapply(make_heatmap_plot, hot = hot) %>% 
    {cowplot::plot_grid(.[[1]], .[[2]], nrow=2)} 
  
  title <- cowplot::ggdraw() + 
    cowplot::draw_label(
      title_txt,
      fontface = 'bold',
    ) +
    theme(
      # add margin on the left of the drawing canvas,
      # so title is aligned with left edge of first plot
      plot.margin = margin(0, 0, 0, 0)
    )
  cowplot::plot_grid(
    title, plt,
    ncol = 1,
    # rel_heights values control vertical title margins
    rel_heights = c(0.1, 1)
  )
}
```

```{r iterate_figures, warning=FALSE}
make_figures <- function(pattern, title, tsfm, hot, fun) {
  out_base <- stringr::str_replace(pattern, ".tif", "")
  dat <- make_boxplot_data(
    files = cmip_files, pattern = pattern,  
    shp=climdiv, attr_id = "NAME", fun=fun,
    tsfm = tsfm
  ) %>% 
    dplyr::mutate(area = climdiv_to_factor(area))
  
  fig <- make_boxplot_plot(
      dat, 
      "Difference", 
      title
    ) 
  ggsave(glue::glue("./figures/{out_base}_box.png"), fig, width=10, height=6)
  
  ### Make Maps
  dat <- make_map_data(
    files = cmip_files, pattern = pattern, 
    fun = fun, shp = climdiv, attr_id = "NAME", tsfm = tsfm
  )
  
  fig <- apply_map_by_scenario(
    dat, hot, title
  )
  
  png(glue::glue("./figures/{out_base}_map.png"), width = 8, height=6, units="in", res=320)
  print(fig)
  dev.off()
  
  if (!(pattern %in% c("con-wet.tif", "con-dry.tif"))) {
    ### Make Heatmaps
    dat <- make_heatmap_data(
      files = cmip_files, pattern = pattern, fun = fun, shp = climdiv, attr_id = "NAME", tsfm = tsfm
    ) %>% 
      dplyr::mutate(area = climdiv_to_factor(area))
    fig <- apply_heatmap_by_scenario(dat, hot, stringr::str_replace(title, "Annual", "Monthly"))
    ggsave(
      glue::glue("./figures/{out_base}_heat.png"), fig, width=8, height=6, bg = "white"
    )
  }

}

tibble::tribble(
  ~pattern, ~title, ~tsfm, ~hot, ~fun, 
  "above90.tif", "Change in # of Days Above 90°F", NULL, TRUE, "sum",
  "con-dry.tif", "Change in # of Consecutive Dry Days", NULL, FALSE, "sum",
  "con-wet.tif", "Change in # of Consecutive Wet Days", NULL, FALSE, "sum",
  "dry-days.tif", "Change in # of Dry Days", NULL, FALSE, "sum",
  "wet-days.tif", "Change in # of Wet Days", NULL, FALSE, "sum",
  "freeze-free.tif", "Change in # of Freeze-Free Days", NULL, TRUE, "sum",
  "pr.tif", "Change in Annual Total Precipitation (in.)", pr_tsfm, FALSE, "sum",
  "tas.tif", "Change in Mean Annual Temperature (°F)", tas_tsfm, TRUE, "mean",
  "tasmax.tif", "Change in Mean Annual Maximum Temperature (°F)", tas_tsfm, TRUE, "mean",
  "tasmin.tif", "Change in Mean Annual Minimum Temperature (°F)", tas_tsfm, TRUE, "mean"
) %>% 
  dplyr::group_by(pattern) %>% 
  dplyr::group_split() %>%
  purrr::map(function(x) {
    print(x)
    make_figures(pattern=x$pattern, title=x$title, tsfm=x$tsfm[[1]], hot=x$hot, fun=x$fun)
  })
```
